icinga:
  required: True
  type: dict
  schema:
    ip:
      required: True
      type: string
    username:
      required: True
      type: string
    password:
      required: True
      type: string
traps:
  required: True
  type: list
  minlength: 1
  schema:
    type: dict
    schema:
      name:
        required: True
        type: string
      snmp:
        required: True
        type: dict
        schema:
          host:
            required: True
            type: string
          oid:
            required: True
            type: string
          payload_type:
            required: False
            type: string
            default: 'value'
            allowed:
              - value
              - json
              - csv
      icinga:
        required: True
        type: dict
        schema:
          host:
            required: True
            type: string
          service:
            required: True
            type: string
          return_code:
            required: True
            type: dict
            schema:
              ok:
                required: True
                type: string
              warning:
                required: False
                default: 'False'
                type: string
              critical:
                required: False
                default: 'False'
                type: string
